name: .NET Core

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Update to Java 17
        distribution: 'adopt'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Install SonarScanner for MSBuild
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Cache SonarQube Scanner
      uses: actions/cache@v2
      with:
        path: ~/.dotnet/tools
        key: ${{ runner.os }}-sonarscanner-${{ hashFiles('**/global.json') }}

    - name: Print Environment Variables
      run: |
        echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}"
        echo "SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}"

    - name: Check SonarQube Server
      run: |
        curl -v "${{ secrets.SONAR_HOST_URL }}/api/server/version"

    - name: Begin SonarQube analysis
      run: dotnet-sonarscanner begin /k:"elmin387_HealthCare-project-API_5cfb6d62-2dce-4a4f-a4a8-d6061174f4dd" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"

    - name: Build project
      run: dotnet build --no-restore

    - name: End SonarQube analysis
      run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
